from app.services.gemini_service import get_gemini_response


def generate_final_report(
    resume_json_string: str, market_brief: str, seniority: str
) -> str:
    prompt = f"""
    You are a world-class AI Career Strategist. Your task is to conduct a detailed analysis of a candidate's resume against a live, up-to-the-minute Market Intelligence Brief. This brief was generated by an advanced AI search engine that synthesizes information from across the web.

    **Candidate Seniority Level:** {seniority}
    **Candidate's Structured Resume (JSON):**
    {resume_json_string}
    ---
    **LIVE Market Intelligence Brief (from Perplexica AI Search Engine):**
    {market_brief}
    ---
    **INSTRUCTIONS:**
    You MUST prioritize the insights from the LIVE Market Intelligence Brief to inform your analysis. Compare the resume DIRECTLY against the live brief's findings.
    
    Generate a professional report in Markdown using EXACTLY the following sections:
    - Identified Field
    - Key Skills (with proficiency estimation based on the resume)
    - Skill Gaps vs. Live Market Demands (Directly reference findings from the brief)
    - ATS Optimization Tips
    - Suitable Job Roles (based on roles mentioned in the brief)
    - Strategic Project Enhancement (Suggest a new project feature that aligns with trends found in the brief)
    - Career Growth Roadmap
    - Final Insight Summary
    """
    return get_gemini_response(prompt)
